# NumPy - Numerical Python

## Criando arrays NumPy

In [2]:
# Importando o NumPy
import numpy as np

### Criando arrays de 1 dimensão

In [3]:
a1D = np.array([1, 2, 3])
a1D

array([1, 2, 3])

In [4]:
# O objeto criado é um ndarray: n-dimensional array
type(a1D)

numpy.ndarray

In [5]:
# Verificando o tipo dos elementos
a1D.dtype

dtype('int32')

In [6]:
b1D = np.array([1, 2, 3], dtype = float)
b1D

array([1., 2., 3.])

In [7]:
b1D.dtype

dtype('float64')

In [8]:
c1D = np.array([1, 2, 3], dtype = str)
c1D

array(['1', '2', '3'], dtype='<U1')

In [9]:
# str > float > int > bool
d1D = np.array([1, 3.14, "NumPy", True])
d1D

array(['1', '3.14', 'NumPy', 'True'], dtype='<U32')

In [10]:
e1D = np.array([1, 3.14, False, True])
e1D

array([1.  , 3.14, 0.  , 1.  ])

In [11]:
e1D.dtype

dtype('float64')

In [12]:
f1D = np.array([1, False, True])
f1D

array([1, 0, 1])

In [13]:
f1D.dtype

dtype('int32')

In [14]:
g1D = np.array([False, True])
g1D

array([False,  True])

In [15]:
g1D.dtype

dtype('bool')

### Criando arrays de 2 dimensões

In [16]:
a2D = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a2D.dtype

dtype('int32')

### Criando arrays de 3 dimensões

In [18]:
a3D = np.array( [ [ [1,2,3], [4,5,6], [7,8,9] ], [ [11,12,13], [14,15,16], [17,18,19] ], [ [21,22,23], [24,25,26], [27,28,29] ]])
a3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

## Outras formas de criar arrays

### Arrays preenchidos com zeros - zeros()

In [19]:
# 1 dimensão
azeros = np.zeros(5)
azeros

array([0., 0., 0., 0., 0.])

In [20]:
# 2 dimensões
bzeros = np.zeros((3, 4)) # 3 linhas e 4 colunas
bzeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# 3 dimensões
czeros = np.zeros((3, 4, 2)) # 3 páginas, 4 linhas e 2 colunas
czeros

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
# 2 dimensões
dzeros = np.zeros((3, 4), dtype = int) # 3 linhas e 4 colunas
dzeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Arrays preenchidos com 1's - ones()

In [23]:
# 1 dimensão
a_um_1D = np.ones(5)
a_um_1D

array([1., 1., 1., 1., 1.])

In [24]:
b_um_1D = np.ones(10, dtype = str)
b_um_1D

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [25]:
c_um_1D = np.ones(5, dtype = int)
c_um_1D

array([1, 1, 1, 1, 1])

In [26]:
# 2 dimensões
d_um_2D = np.ones((4, 3)) # 4 linhas e 3 colunas
d_um_2D

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
# 3 dimensões
e_um_3D = np.ones((5, 2, 3)) 
e_um_3D

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [28]:
# 4 dimensões
f_um_4D = np.ones((3, 4, 2, 3)) 
f_um_4D

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

### Arrays preenchidos com faixas de valores - arange()

In [29]:
# Cria um ndarray preenchido com  os elementos de 0 a n-1
# No exemplo abaixo vai criar um ndarray com os elementos 0 a 9
a1D = np.arange(10)
a1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Cria um ndarray preenchido com os elementos variando entre o valor inicial e o valor final - 1
# Nesse exemplo vai criar um array com os elementos de 5 a 14
b1D = np.arange(5, 15)
b1D

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
# Cria um ndarray preenchido com os elementos variando entre o valor inicial e o valor final - 1, com um determinado step
# No exemplo vai criar um array com os elementos de 5 a 100, com passo 10. Ou seja: 5, 15, 25...95
c1D = np.arange(5,100, 10)
c1D

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

### Criando arrays preenchidos com valores igualmente espaçados - linspace()

In [32]:
# Cria um array com n elementos entre o valor inicial e valor final, igualmente espaçados
d1D = np.linspace(0,10, 2) # Cria um array com 2 valores entre 0 e 10
d1D

array([ 0., 10.])

In [34]:
e1D = np.linspace(0,10, 4, dtype = int) # Cria um array com 2 valores entre 0 e 10
e1D

array([ 0,  3,  6, 10])

In [44]:
f1D = np.linspace(1,1000, endpoint=False) # Se não for passada a quantidade de elementos, o padrão é gerar 50 elementos
f1D

array([  1.  ,  20.98,  40.96,  60.94,  80.92, 100.9 , 120.88, 140.86,
       160.84, 180.82, 200.8 , 220.78, 240.76, 260.74, 280.72, 300.7 ,
       320.68, 340.66, 360.64, 380.62, 400.6 , 420.58, 440.56, 460.54,
       480.52, 500.5 , 520.48, 540.46, 560.44, 580.42, 600.4 , 620.38,
       640.36, 660.34, 680.32, 700.3 , 720.28, 740.26, 760.24, 780.22,
       800.2 , 820.18, 840.16, 860.14, 880.12, 900.1 , 920.08, 940.06,
       960.04, 980.02])

In [36]:
g1D = np.linspace(1,1000, dtype = int) # gerando int, a função simplesmente corta as casas decimais
g1D

array([   1,   21,   41,   62,   82,  102,  123,  143,  164,  184,  204,
        225,  245,  266,  286,  306,  327,  347,  367,  388,  408,  429,
        449,  469,  490,  510,  531,  551,  571,  592,  612,  633,  653,
        673,  694,  714,  734,  755,  775,  796,  816,  836,  857,  877,
        898,  918,  938,  959,  979, 1000])

In [37]:
h1D = np.linspace(0,50, 10, endpoint = True) # O valor final é incluído
h1D


array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [38]:
i1D = np.linspace(0,50, 10, endpoint = False) # O valor final não é incluído
i1D

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

### Criando arrays preenchidos com um único valor passado por parâmetro - full()

In [45]:
a1D = np.full(10, 5) # ndarray contendo 10 números 5
a1D

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [46]:
a2D = np.full((3, 5), 3)  # ndarray de 3 linhas e 5 colunas contendo o número 3
a2D

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [47]:
a3D = np.full((3, 5, 8), -1)  # ndarray de 3 páginas, 5 linhas e 8 colunas contendo o número -1
a3D

array([[[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]]])

### Criando matriz identidade - eye()

In [49]:
ident = np.eye(5, dtype=int) # Cria uma matriz 5x5 preenchida com 1s na diagonal principal e 0 nas posições restantes
ident

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### Criando matriz com elementos aleatórios

In [50]:
a1D = np.random.randint(0, 100, 10) # Cria um ndarray com 10 elementos entre 0 e 99
a1D

array([16, 98,  6, 44, 80, 45, 53, 53, 38, 30])

In [51]:
a2D = np.random.randint(1, 500, (4,5))
a2D

array([[171, 175, 199,  14,  67],
       [ 41, 483, 143, 126, 347],
       [489,  53, 100,   1, 425],
       [335, 356, 472, 274,  90]])

In [54]:
# Gerando 10 combinações para a mega-sena
# Valores vão de 1 a 60, 10 páginas, 1 linha, 6 colunas
a3D = np.random.randint(1,61,(10,1,6)) 
a3D

array([[[29, 52,  6, 43, 60,  1]],

       [[26, 41, 34, 56, 57, 58]],

       [[60, 39, 21, 53, 50, 47]],

       [[42, 49, 45, 43, 50,  9]],

       [[ 4, 41, 52, 17, 41, 26]],

       [[ 2, 18, 45, 40, 53, 31]],

       [[ 5, 54, 48,  2, 20, 52]],

       [[15,  1, 31,  2, 30, 52]],

       [[24, 48, 22, 16, 53, 12]],

       [[31, 44, 38, 43, 15, 56]]])

In [55]:
b1D = np.random.random(10) # Cria um ndarray contendo 10 elementos aleatórios entre 0 e 1
b1D

array([0.25295242, 0.83000821, 0.92636914, 0.43534939, 0.84350417,
       0.63509532, 0.42658483, 0.67973322, 0.34420996, 0.05450211])

In [56]:
c2D = np.random.random((4,5)) # Cria um ndarray de 4 linhas e 5 colunas contendo elementos aleatórios entre 0 e 1
c2D

array([[0.97114645, 0.74917345, 0.07705902, 0.38361432, 0.07503696],
       [0.75071137, 0.74925059, 0.75048413, 0.76446889, 0.78282888],
       [0.59731378, 0.31264607, 0.82613742, 0.37048469, 0.63835911],
       [0.34416333, 0.48223593, 0.86371277, 0.4893152 , 0.54695086]])

In [53]:
mega_sena = np.random.randint(1, 61, 6)
mega_sena

array([15, 59, 36, 22, 37, 10])