# Indexação e fatiamento (slicing)

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([9, 4, 1, 5, 1, 2, 8, 7, 1, 8])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[37, 85, 52, 84, 74],
       [13, 63, 20, 32, 82],
       [66, 85, 67, 54, 46],
       [25, 69, 36, 49, 16]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.48253061, 0.91905988, 0.39742522, 0.16533053, 0.74094557],
        [0.36559556, 0.15097628, 0.83405303, 0.35825551, 0.85615512],
        [0.35888567, 0.05891074, 0.96303495, 0.98233007, 0.16776709],
        [0.1246679 , 0.63446474, 0.65787286, 0.10261504, 0.02957923]],

       [[0.7918011 , 0.02635903, 0.58974747, 0.13145857, 0.63122776],
        [0.53365655, 0.75607181, 0.73725864, 0.94901079, 0.01798678],
        [0.64305698, 0.2940565 , 0.35206989, 0.15313155, 0.23866109],
        [0.24426193, 0.67278129, 0.81918711, 0.80520872, 0.7541699 ]],

       [[0.12073424, 0.23241315, 0.50498096, 0.88668998, 0.9225101 ],
        [0.67959994, 0.463592  , 0.39730847, 0.27172128, 0.23351521],
        [0.48896807, 0.35096627, 0.48637914, 0.63422315, 0.22647463],
        [0.69918068, 0.68940392, 0.74826494, 0.53788155, 0.45454759]]])

### Acessando elementos específicos

In [5]:
# Acessando elementos de um ndarray de 1 dimensão
a1D

array([9, 4, 1, 5, 1, 2, 8, 7, 1, 8])

In [6]:
# nome_do_array[índice]
a1D[0]

9

In [7]:
a1D[2]

1

In [8]:
a1D[-1]

8

In [9]:
indices = [3, 0, -1] # Definindo uma lista com os índices que se deseja acessar
a1D[indices]

array([5, 9, 8])

In [10]:
# Acessando elementos de um ndarray de 2 dimensões
a2D

array([[37, 85, 52, 84, 74],
       [13, 63, 20, 32, 82],
       [66, 85, 67, 54, 46],
       [25, 69, 36, 49, 16]])

In [11]:
# nome_da_matriz[linha][coluna]
a2D[1][2]

20

In [12]:
a2D[3][4]

16

In [13]:
indice_lin = [0, 1, 2, 3]
indice_col = [0, 1, 2, 3]

a2D[indice_lin, indice_col]

array([37, 63, 67, 49])

In [14]:
indice_lin = [0, 1, 2, 3]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([84, 20, 85, 25])

In [15]:
indice_lin = [3, 2, 1, 0]
indice_col = [3, 2, 1, 0]

a2D[indice_lin, indice_col]

array([49, 67, 63, 37])

In [16]:
a2D[:,[0,1,2,0]] 

array([[37, 85, 52, 37],
       [13, 63, 20, 13],
       [66, 85, 67, 66],
       [25, 69, 36, 25]])

In [21]:
a2D[:,[0,1,2,0]][[1, 0, 1, 0]]

array([[13, 63, 20, 13],
       [37, 85, 52, 37],
       [13, 63, 20, 13],
       [37, 85, 52, 37]])

In [18]:
a2D

array([[37, 85, 52, 84, 74],
       [13, 63, 20, 32, 82],
       [66, 85, 67, 54, 46],
       [25, 69, 36, 49, 16]])

In [19]:
a2D[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[13, 63, 20, 13],
       [37, 85, 52, 37],
       [13, 63, 20, 13],
       [37, 85, 52, 37]])

In [22]:
# Acessando elementos de um ndarray de 3 dimensões
a3D

array([[[0.48253061, 0.91905988, 0.39742522, 0.16533053, 0.74094557],
        [0.36559556, 0.15097628, 0.83405303, 0.35825551, 0.85615512],
        [0.35888567, 0.05891074, 0.96303495, 0.98233007, 0.16776709],
        [0.1246679 , 0.63446474, 0.65787286, 0.10261504, 0.02957923]],

       [[0.7918011 , 0.02635903, 0.58974747, 0.13145857, 0.63122776],
        [0.53365655, 0.75607181, 0.73725864, 0.94901079, 0.01798678],
        [0.64305698, 0.2940565 , 0.35206989, 0.15313155, 0.23866109],
        [0.24426193, 0.67278129, 0.81918711, 0.80520872, 0.7541699 ]],

       [[0.12073424, 0.23241315, 0.50498096, 0.88668998, 0.9225101 ],
        [0.67959994, 0.463592  , 0.39730847, 0.27172128, 0.23351521],
        [0.48896807, 0.35096627, 0.48637914, 0.63422315, 0.22647463],
        [0.69918068, 0.68940392, 0.74826494, 0.53788155, 0.45454759]]])

In [23]:
# nome_do_cubo[página][linha][coluna]
a3D[2][0][3]

0.8866899760954104

In [24]:
a3D[0][3][1]

0.634464743749746

### Fatiamento (slicing)

In [25]:
# Array de 1 dimensão
a1D

array([9, 4, 1, 5, 1, 2, 8, 7, 1, 8])

In [27]:
a = a1D[1:5] # Índice 1 ao 4
a

array([4, 1, 5, 1, 2])

In [28]:
b = a1D[0:6] # Índice 0 ao 5
b

array([9, 4, 1, 5, 1, 2])

In [29]:
c = a1D[:6] # Do início ao 5
c

array([9, 4, 1, 5, 1, 2])

In [30]:
d = a1D[::2] # Do início ao fim, com passo 2
d

array([9, 1, 1, 8, 1])

In [31]:
e = a1D[-1::-1] # Do final até o início
e

array([8, 1, 7, 8, 2, 1, 5, 1, 4, 9])

In [32]:
# Array de 2 dimensões
a2D

array([[37, 85, 52, 84, 74],
       [13, 63, 20, 32, 82],
       [66, 85, 67, 54, 46],
       [25, 69, 36, 49, 16]])

In [33]:
linha0 = a2D[0] # Todos os elementos da linha 0 - outra forma seria: linha0 = a2D[0,:]
linha0

array([37, 85, 52, 84, 74])

In [34]:
linha1 = a2D[1,:] # Todos os elementos da linha 1
linha1

array([13, 63, 20, 32, 82])

In [35]:
linha2 = a2D[2,1:4] # Linha 2, colunas 1, 2 e 3
linha2

array([85, 67, 54])

In [36]:
linha3 = a2D[:][3] # a2D[:] retorna toda a matriz, então de toda a matriz queremos a linha 3 a2D[:][3]
linha3

array([25, 69, 36, 49, 16])

In [37]:
coluna2 = a2D[:,2] # De todas as linhas, selecionar a coluna 2
coluna2

array([52, 20, 67, 36])

In [38]:
coluna3 = a2D[1:,3] # Da linha um até a última, selecionar a coluna 3
coluna3

array([32, 54, 49])

In [39]:
# Array de 3 dimensões
a3D

array([[[0.48253061, 0.91905988, 0.39742522, 0.16533053, 0.74094557],
        [0.36559556, 0.15097628, 0.83405303, 0.35825551, 0.85615512],
        [0.35888567, 0.05891074, 0.96303495, 0.98233007, 0.16776709],
        [0.1246679 , 0.63446474, 0.65787286, 0.10261504, 0.02957923]],

       [[0.7918011 , 0.02635903, 0.58974747, 0.13145857, 0.63122776],
        [0.53365655, 0.75607181, 0.73725864, 0.94901079, 0.01798678],
        [0.64305698, 0.2940565 , 0.35206989, 0.15313155, 0.23866109],
        [0.24426193, 0.67278129, 0.81918711, 0.80520872, 0.7541699 ]],

       [[0.12073424, 0.23241315, 0.50498096, 0.88668998, 0.9225101 ],
        [0.67959994, 0.463592  , 0.39730847, 0.27172128, 0.23351521],
        [0.48896807, 0.35096627, 0.48637914, 0.63422315, 0.22647463],
        [0.69918068, 0.68940392, 0.74826494, 0.53788155, 0.45454759]]])

In [40]:
# Acessando a página/face 1
face1 = a3D[1]
face1

array([[0.7918011 , 0.02635903, 0.58974747, 0.13145857, 0.63122776],
       [0.53365655, 0.75607181, 0.73725864, 0.94901079, 0.01798678],
       [0.64305698, 0.2940565 , 0.35206989, 0.15313155, 0.23866109],
       [0.24426193, 0.67278129, 0.81918711, 0.80520872, 0.7541699 ]])

In [41]:
# Acessando uma parte da face1
subface1 = a3D[1,0:3, 1:4]
subface1

array([[0.02635903, 0.58974747, 0.13145857],
       [0.75607181, 0.73725864, 0.94901079],
       [0.2940565 , 0.35206989, 0.15313155]])

In [42]:
linha2face0 = a3D[0,2] # outra forma: linha2face0 = a3D[0,2,:]
linha2face0

array([0.35888567, 0.05891074, 0.96303495, 0.98233007, 0.16776709])

In [43]:
a3D

array([[[0.48253061, 0.91905988, 0.39742522, 0.16533053, 0.74094557],
        [0.36559556, 0.15097628, 0.83405303, 0.35825551, 0.85615512],
        [0.35888567, 0.05891074, 0.96303495, 0.98233007, 0.16776709],
        [0.1246679 , 0.63446474, 0.65787286, 0.10261504, 0.02957923]],

       [[0.7918011 , 0.02635903, 0.58974747, 0.13145857, 0.63122776],
        [0.53365655, 0.75607181, 0.73725864, 0.94901079, 0.01798678],
        [0.64305698, 0.2940565 , 0.35206989, 0.15313155, 0.23866109],
        [0.24426193, 0.67278129, 0.81918711, 0.80520872, 0.7541699 ]],

       [[0.12073424, 0.23241315, 0.50498096, 0.88668998, 0.9225101 ],
        [0.67959994, 0.463592  , 0.39730847, 0.27172128, 0.23351521],
        [0.48896807, 0.35096627, 0.48637914, 0.63422315, 0.22647463],
        [0.69918068, 0.68940392, 0.74826494, 0.53788155, 0.45454759]]])

In [44]:
linha1todasfaces = a3D[:,1] # outra forma: linha1todasfaces = a3D[:,1,:]
linha1todasfaces

array([[0.36559556, 0.15097628, 0.83405303, 0.35825551, 0.85615512],
       [0.53365655, 0.75607181, 0.73725864, 0.94901079, 0.01798678],
       [0.67959994, 0.463592  , 0.39730847, 0.27172128, 0.23351521]])

In [45]:
coluna3todasfaces = a3D[:,:,3]
coluna3todasfaces

array([[0.16533053, 0.35825551, 0.98233007, 0.10261504],
       [0.13145857, 0.94901079, 0.15313155, 0.80520872],
       [0.88668998, 0.27172128, 0.63422315, 0.53788155]])

### Indexação com booleanos

In [46]:
a2D = np.random.randint(1, 501, (10, 8)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[263, 400,  25, 104,  24, 167, 343, 239],
       [125, 405,  73, 493, 102, 118, 164,  70],
       [297, 362, 299, 231, 162, 332,  71, 122],
       [134, 292, 140, 124, 474,  63, 236, 468],
       [358, 476, 366,  62, 237, 257, 233, 172],
       [125,  17,  91,  86, 392, 434, 279, 460],
       [240, 429,  86, 304, 258, 363,  78, 449],
       [418, 489, 415, 360, 390,  79, 233, 119],
       [194, 212, 158, 153, 479, 321, 263, 328],
       [224, 339,  15, 190, 180,  72,  75, 422]])

In [47]:
a2D >= 250

array([[ True,  True, False, False, False, False,  True, False],
       [False,  True, False,  True, False, False, False, False],
       [ True,  True,  True, False, False,  True, False, False],
       [False,  True, False, False,  True, False, False,  True],
       [ True,  True,  True, False, False,  True, False, False],
       [False, False, False, False,  True,  True,  True,  True],
       [False,  True, False,  True,  True,  True, False,  True],
       [ True,  True,  True,  True,  True, False, False, False],
       [False, False, False, False,  True,  True,  True,  True],
       [False,  True, False, False, False, False, False,  True]])

In [48]:
a2D[a2D >= 250]

array([263, 400, 343, 405, 493, 297, 362, 299, 332, 292, 474, 468, 358,
       476, 366, 257, 392, 434, 279, 460, 429, 304, 258, 363, 449, 418,
       489, 415, 360, 390, 479, 321, 263, 328, 339, 422])

In [49]:
a2D.mean()

241.275

In [50]:
a2D[a2D <= a2D.mean()]

array([ 25, 104,  24, 167, 239, 125,  73, 102, 118, 164,  70, 231, 162,
        71, 122, 134, 140, 124,  63, 236,  62, 237, 233, 172, 125,  17,
        91,  86, 240,  86,  78,  79, 233, 119, 194, 212, 158, 153, 224,
        15, 190, 180,  72,  75])