# Verificando propriedades de um ndarray

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([5, 9, 4, 9, 2, 7, 0, 3, 6, 9])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[87, 10, 13, 41, 84],
       [67, 36, 49,  1, 83],
       [88,  3, 88, 48, 70],
       [40, 32, 44, 59, 54]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.71110481, 0.38730651, 0.36003325, 0.58834891, 0.19416811],
        [0.80648995, 0.23550783, 0.31803065, 0.90880742, 0.90364542],
        [0.13954105, 0.54115801, 0.28973236, 0.77297873, 0.04063065],
        [0.15613654, 0.76312864, 0.38377983, 0.93728357, 0.56549299]],

       [[0.00610073, 0.55997863, 0.63406638, 0.09148883, 0.79338706],
        [0.07335096, 0.45826409, 0.67875151, 0.27452885, 0.1297307 ],
        [0.43328421, 0.77420908, 0.53664927, 0.82943039, 0.89584854],
        [0.29190435, 0.51584751, 0.22799574, 0.47907646, 0.98721284]],

       [[0.64628238, 0.16715166, 0.37098627, 0.46449339, 0.45717772],
        [0.31680068, 0.92582187, 0.38624467, 0.62286709, 0.40687578],
        [0.76992165, 0.82638769, 0.16154613, 0.71151819, 0.64061551],
        [0.44666281, 0.95029753, 0.42689236, 0.79414157, 0.12498554]]])

### Verificando o formato e quantidade de dimensões de um array - shape e dim

In [5]:
# A propriedade shape retorna o formato do array
a1D.shape

(10,)

In [6]:
a2D.shape

(4, 5)

In [7]:
a3D.shape

(3, 4, 5)

In [8]:
# A propriedade ndim retorna o números de dimensões do array
a1D.ndim

1

In [9]:
a2D.ndim

2

In [10]:
a3D.ndim

3

### Verificando o tamanho das dimensões de um array - len

In [11]:
len(a1D) # Retorna o tamanho da 1a dimensão (quantidade de colunas)

10

In [12]:
len(a2D) # Retorna o tamanho da 1a dimensão (quantidade de linhas)

4

In [13]:
len(a2D[0]) # Retorna o tamanho da 2a dimensão (quantidade de colunas)

5

In [14]:
len(a3D) # Retorna o tamanho da 1a dimensão (quantidade de páginas)

3

In [15]:
len(a3D[0]) # Retorna o tamanho da 2a dimensão (quantidade de linhas)

4

In [16]:
len(a3D[0][0]) # Retorna o tamanho da 3a dimensão (quantidade de colunas)

5

### Verificando a quantidade de elementos de um array - size

In [17]:
a1D.size

10

In [18]:
a2D.size

20

In [19]:
a3D.size

60

### Verificando o tipo dos elementos um array - dtype

In [20]:
a1D.dtype

dtype('int32')

In [21]:
a1D.dtype.name

'int32'

In [22]:
a2D.dtype

dtype('int32')

In [23]:
a2D.dtype.name

'int32'

In [24]:
a3D.dtype

dtype('float64')

In [25]:
a3D.dtype.name

'float64'